---
title: "Benchmarking"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Benchmarking}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(RcppCoDA)
library(microbenchmark)
```

# Transformation of Large Data
Note the compositions package by default uses columns for parts and rows for samples. In contrast, 
RcppCoDA uses rows for parts and columns for samples. So I make two versions of the data
so that transposition is not counted as part of the computation time. 

```{r}
d <- c(100,1000)
X <- matrix(abs(rnorm(prod(d))), d[1], d[2])
Xt <- t(X)

# Closure 
microbenchmark(
  RcppCoDA::clo(X), 
  compositions::clo(Xt), times=100
)

X <- clo(X)
Xt <- compositions::clo(Xt)

# ALR Transformation
microbenchmark(
  RcppCoDA::alr(X, d=4), 
  compositions::alr(Xt, ivar=4), times=100
)

# ILR Transformation (default basis)
V <- RcppCoDA::ilrContrast(d[1])
Vt <- t(V)
microbenchmark(
  RcppCoDA::ilr(X, V), 
  compositions::ilr(Xt, Vt), times=100
)

# CLR Transformation
microbenchmark(
  RcppCoDA::clr(X), 
  compositions::clr(Xt), times=100
)
```

Now this is where the real speed ups come in, when working with array structures:
```{r}
A <- array(X, dim=c(d, 100))
A <- RcppCoDA::clo(A) # automatically an array closure on the first dimension 
At <- aperm(A, c(2,1,3))

# compositions has no explicit handing of arrays. RcppCoDA can handle multi-dimensional arrays, 
# here we will only look at 3D arrays as this is easiest to code for compositions
alr_array_compositions <- function(X, d){
  dd <- dim(X)
  dd[1] <- dd[1]-1
  Y <- array(0, dim=dd)
  for (i in 1:dd[3]){
    Y[,,i] <- alr(X[,,i], d)
  }
  return(Y)
}

microbenchmark(
  alr(A, 4), 
  alr_array_compositions(At, 4), 
  times=1
)
```

