// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// clo_internal
Eigen::MatrixXd clo_internal(Eigen::Map<Eigen::MatrixXd> X);
RcppExport SEXP _RcppCoDA_clo_internal(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(clo_internal(X));
    return rcpp_result_gen;
END_RCPP
}
// center_internal
Eigen::MatrixXd center_internal(Eigen::Map<Eigen::MatrixXd> X);
RcppExport SEXP _RcppCoDA_center_internal(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(center_internal(X));
    return rcpp_result_gen;
END_RCPP
}
// alrContrast
Eigen::MatrixXd alrContrast(int D, int d, bool inv);
RcppExport SEXP _RcppCoDA_alrContrast(SEXP DSEXP, SEXP dSEXP, SEXP invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type inv(invSEXP);
    rcpp_result_gen = Rcpp::wrap(alrContrast(D, d, inv));
    return rcpp_result_gen;
END_RCPP
}
// clrContrast
Eigen::MatrixXd clrContrast(int D, bool inv);
RcppExport SEXP _RcppCoDA_clrContrast(SEXP DSEXP, SEXP invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< bool >::type inv(invSEXP);
    rcpp_result_gen = Rcpp::wrap(clrContrast(D, inv));
    return rcpp_result_gen;
END_RCPP
}
// ilrContrast
Eigen::MatrixXd ilrContrast(int D);
RcppExport SEXP _RcppCoDA_ilrContrast(SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(ilrContrast(D));
    return rcpp_result_gen;
END_RCPP
}
// glr_internal
Eigen::MatrixXd glr_internal(Eigen::Map<Eigen::MatrixXd>& X, Eigen::Map<Eigen::MatrixXd>& V);
RcppExport SEXP _RcppCoDA_glr_internal(SEXP XSEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(glr_internal(X, V));
    return rcpp_result_gen;
END_RCPP
}
// glrInv_internal
Eigen::MatrixXd glrInv_internal(Eigen::Map<Eigen::MatrixXd>& X, Eigen::Map<Eigen::MatrixXd>& V);
RcppExport SEXP _RcppCoDA_glrInv_internal(SEXP XSEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(glrInv_internal(X, V));
    return rcpp_result_gen;
END_RCPP
}
// alr_internal
Eigen::MatrixXd alr_internal(Eigen::Map<Eigen::MatrixXd>& X, int d);
RcppExport SEXP _RcppCoDA_alr_internal(SEXP XSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(alr_internal(X, d));
    return rcpp_result_gen;
END_RCPP
}
// alrInv_internal
Eigen::MatrixXd alrInv_internal(Eigen::Map<Eigen::MatrixXd>& X, int d);
RcppExport SEXP _RcppCoDA_alrInv_internal(SEXP XSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(alrInv_internal(X, d));
    return rcpp_result_gen;
END_RCPP
}
// clr_internal
Eigen::MatrixXd clr_internal(Eigen::Map<Eigen::MatrixXd>& X);
RcppExport SEXP _RcppCoDA_clr_internal(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(clr_internal(X));
    return rcpp_result_gen;
END_RCPP
}
// clrInv_internal
Eigen::MatrixXd clrInv_internal(Eigen::Map<Eigen::MatrixXd>& X);
RcppExport SEXP _RcppCoDA_clrInv_internal(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(clrInv_internal(X));
    return rcpp_result_gen;
END_RCPP
}
// ilr_internal
Eigen::MatrixXd ilr_internal(Eigen::Map<Eigen::MatrixXd>& X, Rcpp::Nullable<Eigen::Map<Eigen::MatrixXd>&> V);
RcppExport SEXP _RcppCoDA_ilr_internal(SEXP XSEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Eigen::Map<Eigen::MatrixXd>&> >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(ilr_internal(X, V));
    return rcpp_result_gen;
END_RCPP
}
// ilrInv_internal
Eigen::MatrixXd ilrInv_internal(Eigen::Map<Eigen::MatrixXd>& X, Rcpp::Nullable<Eigen::Map<Eigen::MatrixXd>&> V);
RcppExport SEXP _RcppCoDA_ilrInv_internal(SEXP XSEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Eigen::Map<Eigen::MatrixXd>&> >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(ilrInv_internal(X, V));
    return rcpp_result_gen;
END_RCPP
}
// iiContrast
Eigen::MatrixXd iiContrast(Eigen::Map<Eigen::MatrixXd>& V1, Eigen::Map<Eigen::MatrixXd>& V2);
RcppExport SEXP _RcppCoDA_iiContrast(SEXP V1SEXP, SEXP V2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type V1(V1SEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type V2(V2SEXP);
    rcpp_result_gen = Rcpp::wrap(iiContrast(V1, V2));
    return rcpp_result_gen;
END_RCPP
}
// icContrast
Eigen::MatrixXd icContrast(Eigen::Map<Eigen::MatrixXd>& V1);
RcppExport SEXP _RcppCoDA_icContrast(SEXP V1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type V1(V1SEXP);
    rcpp_result_gen = Rcpp::wrap(icContrast(V1));
    return rcpp_result_gen;
END_RCPP
}
// ciContrast
Eigen::MatrixXd ciContrast(Eigen::Map<Eigen::MatrixXd>& V2);
RcppExport SEXP _RcppCoDA_ciContrast(SEXP V2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type V2(V2SEXP);
    rcpp_result_gen = Rcpp::wrap(ciContrast(V2));
    return rcpp_result_gen;
END_RCPP
}
// iaContrast
Eigen::MatrixXd iaContrast(Eigen::Map<Eigen::MatrixXd>& V1, int d2, int D);
RcppExport SEXP _RcppCoDA_iaContrast(SEXP V1SEXP, SEXP d2SEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type V1(V1SEXP);
    Rcpp::traits::input_parameter< int >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(iaContrast(V1, d2, D));
    return rcpp_result_gen;
END_RCPP
}
// aiContrast
Eigen::MatrixXd aiContrast(int d2, Eigen::Map<Eigen::MatrixXd>& V2, int D);
RcppExport SEXP _RcppCoDA_aiContrast(SEXP d2SEXP, SEXP V2SEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type V2(V2SEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(aiContrast(d2, V2, D));
    return rcpp_result_gen;
END_RCPP
}
// caContrast
Eigen::MatrixXd caContrast(int d2, int D);
RcppExport SEXP _RcppCoDA_caContrast(SEXP d2SEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(caContrast(d2, D));
    return rcpp_result_gen;
END_RCPP
}
// acContrast
Eigen::MatrixXd acContrast(int d1, int D);
RcppExport SEXP _RcppCoDA_acContrast(SEXP d1SEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(acContrast(d1, D));
    return rcpp_result_gen;
END_RCPP
}
// aaContrast
Eigen::MatrixXd aaContrast(int d1, int d2, int D);
RcppExport SEXP _RcppCoDA_aaContrast(SEXP d1SEXP, SEXP d2SEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< int >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(aaContrast(d1, d2, D));
    return rcpp_result_gen;
END_RCPP
}
// ilr2ilr_internal
Eigen::MatrixXd ilr2ilr_internal(Eigen::Map<Eigen::MatrixXd>& X, Eigen::Map<Eigen::MatrixXd>& V1, Eigen::Map<Eigen::MatrixXd>& V2);
RcppExport SEXP _RcppCoDA_ilr2ilr_internal(SEXP XSEXP, SEXP V1SEXP, SEXP V2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type V1(V1SEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type V2(V2SEXP);
    rcpp_result_gen = Rcpp::wrap(ilr2ilr_internal(X, V1, V2));
    return rcpp_result_gen;
END_RCPP
}
// ilr2clr_internal
Eigen::MatrixXd ilr2clr_internal(Eigen::Map<Eigen::MatrixXd>& X, Eigen::Map<Eigen::MatrixXd>& V1);
RcppExport SEXP _RcppCoDA_ilr2clr_internal(SEXP XSEXP, SEXP V1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type V1(V1SEXP);
    rcpp_result_gen = Rcpp::wrap(ilr2clr_internal(X, V1));
    return rcpp_result_gen;
END_RCPP
}
// clr2ilr_internal
Eigen::MatrixXd clr2ilr_internal(Eigen::Map<Eigen::MatrixXd>& X, Eigen::Map<Eigen::MatrixXd>& V2);
RcppExport SEXP _RcppCoDA_clr2ilr_internal(SEXP XSEXP, SEXP V2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type V2(V2SEXP);
    rcpp_result_gen = Rcpp::wrap(clr2ilr_internal(X, V2));
    return rcpp_result_gen;
END_RCPP
}
// alr2clr_internal
Eigen::MatrixXd alr2clr_internal(Eigen::Map<Eigen::MatrixXd>& X, int d1);
RcppExport SEXP _RcppCoDA_alr2clr_internal(SEXP XSEXP, SEXP d1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type d1(d1SEXP);
    rcpp_result_gen = Rcpp::wrap(alr2clr_internal(X, d1));
    return rcpp_result_gen;
END_RCPP
}
// clr2alr_internal
Eigen::MatrixXd clr2alr_internal(Eigen::Map<Eigen::MatrixXd>& X, int d2);
RcppExport SEXP _RcppCoDA_clr2alr_internal(SEXP XSEXP, SEXP d2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type d2(d2SEXP);
    rcpp_result_gen = Rcpp::wrap(clr2alr_internal(X, d2));
    return rcpp_result_gen;
END_RCPP
}
// alr2alr_internal
Eigen::MatrixXd alr2alr_internal(Eigen::Map<Eigen::MatrixXd>& X, int d1, int d2);
RcppExport SEXP _RcppCoDA_alr2alr_internal(SEXP XSEXP, SEXP d1SEXP, SEXP d2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< int >::type d2(d2SEXP);
    rcpp_result_gen = Rcpp::wrap(alr2alr_internal(X, d1, d2));
    return rcpp_result_gen;
END_RCPP
}
// ilr2alr_internal
Eigen::MatrixXd ilr2alr_internal(Eigen::Map<Eigen::MatrixXd>& X, Eigen::Map<Eigen::MatrixXd>& V1, int d2);
RcppExport SEXP _RcppCoDA_ilr2alr_internal(SEXP XSEXP, SEXP V1SEXP, SEXP d2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type V1(V1SEXP);
    Rcpp::traits::input_parameter< int >::type d2(d2SEXP);
    rcpp_result_gen = Rcpp::wrap(ilr2alr_internal(X, V1, d2));
    return rcpp_result_gen;
END_RCPP
}
// alr2ilr_internal
Eigen::MatrixXd alr2ilr_internal(Eigen::Map<Eigen::MatrixXd>& X, int d1, Eigen::Map<Eigen::MatrixXd>& V2);
RcppExport SEXP _RcppCoDA_alr2ilr_internal(SEXP XSEXP, SEXP d1SEXP, SEXP V2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type V2(V2SEXP);
    rcpp_result_gen = Rcpp::wrap(alr2ilr_internal(X, d1, V2));
    return rcpp_result_gen;
END_RCPP
}
// ilrvar2ilrvar_internal
Eigen::MatrixXd ilrvar2ilrvar_internal(Eigen::Map<Eigen::MatrixXd>& Sigma, Eigen::Map<Eigen::MatrixXd>& V1, Eigen::Map<Eigen::MatrixXd>& V2);
RcppExport SEXP _RcppCoDA_ilrvar2ilrvar_internal(SEXP SigmaSEXP, SEXP V1SEXP, SEXP V2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type V1(V1SEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type V2(V2SEXP);
    rcpp_result_gen = Rcpp::wrap(ilrvar2ilrvar_internal(Sigma, V1, V2));
    return rcpp_result_gen;
END_RCPP
}
// ilrvar2clrvar_internal
Eigen::MatrixXd ilrvar2clrvar_internal(Eigen::Map<Eigen::MatrixXd>& Sigma, Eigen::Map<Eigen::MatrixXd>& V1);
RcppExport SEXP _RcppCoDA_ilrvar2clrvar_internal(SEXP SigmaSEXP, SEXP V1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type V1(V1SEXP);
    rcpp_result_gen = Rcpp::wrap(ilrvar2clrvar_internal(Sigma, V1));
    return rcpp_result_gen;
END_RCPP
}
// clrvar2ilrvar_internal
Eigen::MatrixXd clrvar2ilrvar_internal(Eigen::Map<Eigen::MatrixXd>& Sigma, Eigen::Map<Eigen::MatrixXd>& V2);
RcppExport SEXP _RcppCoDA_clrvar2ilrvar_internal(SEXP SigmaSEXP, SEXP V2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type V2(V2SEXP);
    rcpp_result_gen = Rcpp::wrap(clrvar2ilrvar_internal(Sigma, V2));
    return rcpp_result_gen;
END_RCPP
}
// alrvar2clrvar_internal
Eigen::MatrixXd alrvar2clrvar_internal(Eigen::Map<Eigen::MatrixXd>& Sigma, int d1);
RcppExport SEXP _RcppCoDA_alrvar2clrvar_internal(SEXP SigmaSEXP, SEXP d1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< int >::type d1(d1SEXP);
    rcpp_result_gen = Rcpp::wrap(alrvar2clrvar_internal(Sigma, d1));
    return rcpp_result_gen;
END_RCPP
}
// clrvar2alrvar_internal
Eigen::MatrixXd clrvar2alrvar_internal(Eigen::Map<Eigen::MatrixXd>& Sigma, int d2);
RcppExport SEXP _RcppCoDA_clrvar2alrvar_internal(SEXP SigmaSEXP, SEXP d2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< int >::type d2(d2SEXP);
    rcpp_result_gen = Rcpp::wrap(clrvar2alrvar_internal(Sigma, d2));
    return rcpp_result_gen;
END_RCPP
}
// alrvar2alrvar_internal
Eigen::MatrixXd alrvar2alrvar_internal(Eigen::Map<Eigen::MatrixXd>& Sigma, int d1, int d2);
RcppExport SEXP _RcppCoDA_alrvar2alrvar_internal(SEXP SigmaSEXP, SEXP d1SEXP, SEXP d2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< int >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< int >::type d2(d2SEXP);
    rcpp_result_gen = Rcpp::wrap(alrvar2alrvar_internal(Sigma, d1, d2));
    return rcpp_result_gen;
END_RCPP
}
// ilrvar2alrvar_internal
Eigen::MatrixXd ilrvar2alrvar_internal(Eigen::Map<Eigen::MatrixXd>& Sigma, Eigen::Map<Eigen::MatrixXd>& V1, int d2);
RcppExport SEXP _RcppCoDA_ilrvar2alrvar_internal(SEXP SigmaSEXP, SEXP V1SEXP, SEXP d2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type V1(V1SEXP);
    Rcpp::traits::input_parameter< int >::type d2(d2SEXP);
    rcpp_result_gen = Rcpp::wrap(ilrvar2alrvar_internal(Sigma, V1, d2));
    return rcpp_result_gen;
END_RCPP
}
// alrvar2ilrvar_internal
Eigen::MatrixXd alrvar2ilrvar_internal(Eigen::Map<Eigen::MatrixXd>& Sigma, int d1, Eigen::Map<Eigen::MatrixXd>& V2);
RcppExport SEXP _RcppCoDA_alrvar2ilrvar_internal(SEXP SigmaSEXP, SEXP d1SEXP, SEXP V2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< int >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type V2(V2SEXP);
    rcpp_result_gen = Rcpp::wrap(alrvar2ilrvar_internal(Sigma, d1, V2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppCoDA_clo_internal", (DL_FUNC) &_RcppCoDA_clo_internal, 1},
    {"_RcppCoDA_center_internal", (DL_FUNC) &_RcppCoDA_center_internal, 1},
    {"_RcppCoDA_alrContrast", (DL_FUNC) &_RcppCoDA_alrContrast, 3},
    {"_RcppCoDA_clrContrast", (DL_FUNC) &_RcppCoDA_clrContrast, 2},
    {"_RcppCoDA_ilrContrast", (DL_FUNC) &_RcppCoDA_ilrContrast, 1},
    {"_RcppCoDA_glr_internal", (DL_FUNC) &_RcppCoDA_glr_internal, 2},
    {"_RcppCoDA_glrInv_internal", (DL_FUNC) &_RcppCoDA_glrInv_internal, 2},
    {"_RcppCoDA_alr_internal", (DL_FUNC) &_RcppCoDA_alr_internal, 2},
    {"_RcppCoDA_alrInv_internal", (DL_FUNC) &_RcppCoDA_alrInv_internal, 2},
    {"_RcppCoDA_clr_internal", (DL_FUNC) &_RcppCoDA_clr_internal, 1},
    {"_RcppCoDA_clrInv_internal", (DL_FUNC) &_RcppCoDA_clrInv_internal, 1},
    {"_RcppCoDA_ilr_internal", (DL_FUNC) &_RcppCoDA_ilr_internal, 2},
    {"_RcppCoDA_ilrInv_internal", (DL_FUNC) &_RcppCoDA_ilrInv_internal, 2},
    {"_RcppCoDA_iiContrast", (DL_FUNC) &_RcppCoDA_iiContrast, 2},
    {"_RcppCoDA_icContrast", (DL_FUNC) &_RcppCoDA_icContrast, 1},
    {"_RcppCoDA_ciContrast", (DL_FUNC) &_RcppCoDA_ciContrast, 1},
    {"_RcppCoDA_iaContrast", (DL_FUNC) &_RcppCoDA_iaContrast, 3},
    {"_RcppCoDA_aiContrast", (DL_FUNC) &_RcppCoDA_aiContrast, 3},
    {"_RcppCoDA_caContrast", (DL_FUNC) &_RcppCoDA_caContrast, 2},
    {"_RcppCoDA_acContrast", (DL_FUNC) &_RcppCoDA_acContrast, 2},
    {"_RcppCoDA_aaContrast", (DL_FUNC) &_RcppCoDA_aaContrast, 3},
    {"_RcppCoDA_ilr2ilr_internal", (DL_FUNC) &_RcppCoDA_ilr2ilr_internal, 3},
    {"_RcppCoDA_ilr2clr_internal", (DL_FUNC) &_RcppCoDA_ilr2clr_internal, 2},
    {"_RcppCoDA_clr2ilr_internal", (DL_FUNC) &_RcppCoDA_clr2ilr_internal, 2},
    {"_RcppCoDA_alr2clr_internal", (DL_FUNC) &_RcppCoDA_alr2clr_internal, 2},
    {"_RcppCoDA_clr2alr_internal", (DL_FUNC) &_RcppCoDA_clr2alr_internal, 2},
    {"_RcppCoDA_alr2alr_internal", (DL_FUNC) &_RcppCoDA_alr2alr_internal, 3},
    {"_RcppCoDA_ilr2alr_internal", (DL_FUNC) &_RcppCoDA_ilr2alr_internal, 3},
    {"_RcppCoDA_alr2ilr_internal", (DL_FUNC) &_RcppCoDA_alr2ilr_internal, 3},
    {"_RcppCoDA_ilrvar2ilrvar_internal", (DL_FUNC) &_RcppCoDA_ilrvar2ilrvar_internal, 3},
    {"_RcppCoDA_ilrvar2clrvar_internal", (DL_FUNC) &_RcppCoDA_ilrvar2clrvar_internal, 2},
    {"_RcppCoDA_clrvar2ilrvar_internal", (DL_FUNC) &_RcppCoDA_clrvar2ilrvar_internal, 2},
    {"_RcppCoDA_alrvar2clrvar_internal", (DL_FUNC) &_RcppCoDA_alrvar2clrvar_internal, 2},
    {"_RcppCoDA_clrvar2alrvar_internal", (DL_FUNC) &_RcppCoDA_clrvar2alrvar_internal, 2},
    {"_RcppCoDA_alrvar2alrvar_internal", (DL_FUNC) &_RcppCoDA_alrvar2alrvar_internal, 3},
    {"_RcppCoDA_ilrvar2alrvar_internal", (DL_FUNC) &_RcppCoDA_ilrvar2alrvar_internal, 3},
    {"_RcppCoDA_alrvar2ilrvar_internal", (DL_FUNC) &_RcppCoDA_alrvar2ilrvar_internal, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppCoDA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
