# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

clo_internal <- function(X) {
    .Call('_RcppCoDA_clo_internal', PACKAGE = 'RcppCoDA', X)
}

center_internal <- function(X) {
    .Call('_RcppCoDA_center_internal', PACKAGE = 'RcppCoDA', X)
}

#' @rdname base_lr_transforms
#' @export
alrContrast <- function(d, D, inv) {
    .Call('_RcppCoDA_alrContrast', PACKAGE = 'RcppCoDA', d, D, inv)
}

#' @rdname base_lr_transforms
#' @export
clrContrast <- function(D, inv) {
    .Call('_RcppCoDA_clrContrast', PACKAGE = 'RcppCoDA', D, inv)
}

#' @rdname base_lr_transforms
#' @export
ilrContrast <- function(D) {
    .Call('_RcppCoDA_ilrContrast', PACKAGE = 'RcppCoDA', D)
}

glr_internal <- function(X, V) {
    .Call('_RcppCoDA_glr_internal', PACKAGE = 'RcppCoDA', X, V)
}

glrInv_internal <- function(X, V) {
    .Call('_RcppCoDA_glrInv_internal', PACKAGE = 'RcppCoDA', X, V)
}

alr_internal <- function(X, d) {
    .Call('_RcppCoDA_alr_internal', PACKAGE = 'RcppCoDA', X, d)
}

alrInv_internal <- function(X, d) {
    .Call('_RcppCoDA_alrInv_internal', PACKAGE = 'RcppCoDA', X, d)
}

clr_internal <- function(X) {
    .Call('_RcppCoDA_clr_internal', PACKAGE = 'RcppCoDA', X)
}

clrInv_internal <- function(X) {
    .Call('_RcppCoDA_clrInv_internal', PACKAGE = 'RcppCoDA', X)
}

ilr_internal <- function(X, V = NULL) {
    .Call('_RcppCoDA_ilr_internal', PACKAGE = 'RcppCoDA', X, V)
}

ilrInv_internal <- function(X, V = NULL) {
    .Call('_RcppCoDA_ilrInv_internal', PACKAGE = 'RcppCoDA', X, V)
}

#' @rdname convert_coda
iiContrast <- function(V1, V2) {
    .Call('_RcppCoDA_iiContrast', PACKAGE = 'RcppCoDA', V1, V2)
}

#' @rdname convert_coda
#' @export
icContrast <- function(V1) {
    .Call('_RcppCoDA_icContrast', PACKAGE = 'RcppCoDA', V1)
}

#' @rdname convert_coda
#' @export
ciContrast <- function(V2) {
    .Call('_RcppCoDA_ciContrast', PACKAGE = 'RcppCoDA', V2)
}

#' @rdname convert_coda
#' @export
iaContrast <- function(V1, d2, D) {
    .Call('_RcppCoDA_iaContrast', PACKAGE = 'RcppCoDA', V1, d2, D)
}

#' @rdname convert_coda
#' @export
aiContrast <- function(d2, V2, D) {
    .Call('_RcppCoDA_aiContrast', PACKAGE = 'RcppCoDA', d2, V2, D)
}

#' @rdname convert_coda
#' @export
caContrast <- function(d2, D) {
    .Call('_RcppCoDA_caContrast', PACKAGE = 'RcppCoDA', d2, D)
}

#' @rdname convert_coda
#' @export
acContrast <- function(d1, D) {
    .Call('_RcppCoDA_acContrast', PACKAGE = 'RcppCoDA', d1, D)
}

#' @rdname convert_coda
#' @export
aaContrast <- function(d1, d2, D) {
    .Call('_RcppCoDA_aaContrast', PACKAGE = 'RcppCoDA', d1, d2, D)
}

ilr2ilr_internal <- function(X, V1, V2) {
    .Call('_RcppCoDA_ilr2ilr_internal', PACKAGE = 'RcppCoDA', X, V1, V2)
}

ilr2clr_internal <- function(X, V1) {
    .Call('_RcppCoDA_ilr2clr_internal', PACKAGE = 'RcppCoDA', X, V1)
}

clr2ilr_internal <- function(X, V2) {
    .Call('_RcppCoDA_clr2ilr_internal', PACKAGE = 'RcppCoDA', X, V2)
}

alr2clr_internal <- function(X, d1) {
    .Call('_RcppCoDA_alr2clr_internal', PACKAGE = 'RcppCoDA', X, d1)
}

clr2alr_internal <- function(X, d2) {
    .Call('_RcppCoDA_clr2alr_internal', PACKAGE = 'RcppCoDA', X, d2)
}

alr2alr_internal <- function(X, d1, d2) {
    .Call('_RcppCoDA_alr2alr_internal', PACKAGE = 'RcppCoDA', X, d1, d2)
}

ilr2alr_internal <- function(X, V1, d2) {
    .Call('_RcppCoDA_ilr2alr_internal', PACKAGE = 'RcppCoDA', X, V1, d2)
}

alr2ilr_internal <- function(X, d1, V2) {
    .Call('_RcppCoDA_alr2ilr_internal', PACKAGE = 'RcppCoDA', X, d1, V2)
}

ilrvar2ilrvar_internal <- function(Sigma, V1, V2) {
    .Call('_RcppCoDA_ilrvar2ilrvar_internal', PACKAGE = 'RcppCoDA', Sigma, V1, V2)
}

ilrvar2clrvar_internal <- function(Sigma, V1) {
    .Call('_RcppCoDA_ilrvar2clrvar_internal', PACKAGE = 'RcppCoDA', Sigma, V1)
}

clrvar2ilrvar_internal <- function(Sigma, V2) {
    .Call('_RcppCoDA_clrvar2ilrvar_internal', PACKAGE = 'RcppCoDA', Sigma, V2)
}

alrvar2clrvar_internal <- function(Sigma, d1) {
    .Call('_RcppCoDA_alrvar2clrvar_internal', PACKAGE = 'RcppCoDA', Sigma, d1)
}

clrvar2alrvar_internal <- function(Sigma, d2) {
    .Call('_RcppCoDA_clrvar2alrvar_internal', PACKAGE = 'RcppCoDA', Sigma, d2)
}

alrvar2alrvar_internal <- function(Sigma, d1, d2) {
    .Call('_RcppCoDA_alrvar2alrvar_internal', PACKAGE = 'RcppCoDA', Sigma, d1, d2)
}

ilrvar2alrvar_internal <- function(Sigma, V1, d2) {
    .Call('_RcppCoDA_ilrvar2alrvar_internal', PACKAGE = 'RcppCoDA', Sigma, V1, d2)
}

alrvar2ilrvar_internal <- function(Sigma, d1, V2) {
    .Call('_RcppCoDA_alrvar2ilrvar_internal', PACKAGE = 'RcppCoDA', Sigma, d1, V2)
}

clrvar2phi_internal <- function(Sigma) {
    .Call('_RcppCoDA_clrvar2phi_internal', PACKAGE = 'RcppCoDA', Sigma)
}

