# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

clo_internal <- function(X) {
    .Call('_RcppCoDA_clo_internal', PACKAGE = 'RcppCoDA', X)
}

center_internal <- function(X) {
    .Call('_RcppCoDA_center_internal', PACKAGE = 'RcppCoDA', X)
}

#' @rdname base_lr_transforms
alrContrast <- function(D, d, inv) {
    .Call('_RcppCoDA_alrContrast', PACKAGE = 'RcppCoDA', D, d, inv)
}

#' @rdname base_lr_transforms
#' @export
clrContrast <- function(D, inv) {
    .Call('_RcppCoDA_clrContrast', PACKAGE = 'RcppCoDA', D, inv)
}

#' @rdname base_lr_transforms
#' @export
ilrContrast <- function(D) {
    .Call('_RcppCoDA_ilrContrast', PACKAGE = 'RcppCoDA', D)
}

glr_internal <- function(X, V) {
    .Call('_RcppCoDA_glr_internal', PACKAGE = 'RcppCoDA', X, V)
}

glrInv_internal <- function(X, V) {
    .Call('_RcppCoDA_glrInv_internal', PACKAGE = 'RcppCoDA', X, V)
}

alr_internal <- function(X, d) {
    .Call('_RcppCoDA_alr_internal', PACKAGE = 'RcppCoDA', X, d)
}

alrInv_internal <- function(X, d) {
    .Call('_RcppCoDA_alrInv_internal', PACKAGE = 'RcppCoDA', X, d)
}

clr_internal <- function(X) {
    .Call('_RcppCoDA_clr_internal', PACKAGE = 'RcppCoDA', X)
}

clrInv_internal <- function(X) {
    .Call('_RcppCoDA_clrInv_internal', PACKAGE = 'RcppCoDA', X)
}

ilr_internal <- function(X, V = NULL) {
    .Call('_RcppCoDA_ilr_internal', PACKAGE = 'RcppCoDA', X, V)
}

ilrInv_internal <- function(X, V = NULL) {
    .Call('_RcppCoDA_ilrInv_internal', PACKAGE = 'RcppCoDA', X, V)
}

#' Transfer data and covariance matricies from one coordinate system to another
#' 
#' Naming Conventions:
#' xxContrast produces a contrast matrix for transforming between representations where 
#' i=ILR, c=CLR, a=ALR. x2x represent transformations of data between coordinate systems 
#' xvar2xvar represent transformations of covariance matricies between coordinate systems. 
#' By convention all functions take arguments as follows: all functions have the form function(a,b,c)
#' where a is the data/covariance, b is the argument for specifying the current coordinate system, and c 
#' represents the argument for specifying the desired coordinate system. 
#' @param X data to transform between representations (parts/coords x samples)
#' @param Sigma covariance matrix in specified transformed space
#' @param V ILR contrast matrix (i.e., transformation matrix of ILR)
#' @param V1 ILR contrast matrix of basis Sigma is already in
#' @param V2 ILR contrast matrix of basis Sigma is desired in
#' @param d1 alr reference element Sigma is already expressed with respec to
#' @param d2 alr reference element Sigma is to be expressed with respect to
#' @return matrix
#' @name convert_coda
#' @export
#' @examples
#' # For Data
#' X <- matrix(abs(rnorm(10)), 5, 2)
#' X <- clo(X)
#' X.clr <- clr(X)
#' X.alr <- clr2alr(X, 3)
#' 
#' # For a covariance matrix starting in the alr
#' Sigma.alr <- X.alr%*%t(X.alr) # Just a random covariance matrix 
#' Sigma.ilr <- alrvar2ilrvar(Sigma.alr, 3, ilrContrast(5)) # Covert to default ILR
#' 
#' # Another way of doing this more "manually" - use contrast matricies
#' V <- caContrast(3, nrow(X)) # create contrast from clr to alr
#' X.alr <- V %*% X.clr
iiContrast <- function(V1, V2) {
    .Call('_RcppCoDA_iiContrast', PACKAGE = 'RcppCoDA', V1, V2)
}

#' @rdname convert_coda
#' @export
icContrast <- function(V1) {
    .Call('_RcppCoDA_icContrast', PACKAGE = 'RcppCoDA', V1)
}

#' @rdname convert_coda
#' @export
ciContrast <- function(V2) {
    .Call('_RcppCoDA_ciContrast', PACKAGE = 'RcppCoDA', V2)
}

#' @rdname convert_coda
#' @export
iaContrast <- function(V1, d2, D) {
    .Call('_RcppCoDA_iaContrast', PACKAGE = 'RcppCoDA', V1, d2, D)
}

#' @rdname convert_coda
#' @export
aiContrast <- function(d2, V2, D) {
    .Call('_RcppCoDA_aiContrast', PACKAGE = 'RcppCoDA', d2, V2, D)
}

#' @rdname convert_coda
#' @export
caContrast <- function(d2, D) {
    .Call('_RcppCoDA_caContrast', PACKAGE = 'RcppCoDA', d2, D)
}

#' @rdname convert_coda
#' @export
acContrast <- function(d1, D) {
    .Call('_RcppCoDA_acContrast', PACKAGE = 'RcppCoDA', d1, D)
}

#' @rdname convert_coda
#' @export
aaContrast <- function(d1, d2, D) {
    .Call('_RcppCoDA_aaContrast', PACKAGE = 'RcppCoDA', d1, d2, D)
}

#' @rdname convert_coda
#' @export
ilr2ilr <- function(X, V1, V2) {
    .Call('_RcppCoDA_ilr2ilr', PACKAGE = 'RcppCoDA', X, V1, V2)
}

#' @rdname convert_coda
#' @export
ilr2clr <- function(X, V1) {
    .Call('_RcppCoDA_ilr2clr', PACKAGE = 'RcppCoDA', X, V1)
}

#' @rdname convert_coda
#' @export
clr2ilr <- function(X, V2) {
    .Call('_RcppCoDA_clr2ilr', PACKAGE = 'RcppCoDA', X, V2)
}

#' @rdname convert_coda
#' @export
alr2clr <- function(X, d1) {
    .Call('_RcppCoDA_alr2clr', PACKAGE = 'RcppCoDA', X, d1)
}

#' @rdname convert_coda
#' @export
clr2alr <- function(X, d2) {
    .Call('_RcppCoDA_clr2alr', PACKAGE = 'RcppCoDA', X, d2)
}

#' @rdname convert_coda
#' @export
alr2alr <- function(X, d1, d2) {
    .Call('_RcppCoDA_alr2alr', PACKAGE = 'RcppCoDA', X, d1, d2)
}

#' @rdname convert_coda
#' @export
ilr2alr <- function(X, V1, d2) {
    .Call('_RcppCoDA_ilr2alr', PACKAGE = 'RcppCoDA', X, V1, d2)
}

#' @rdname convert_coda
#' @export
alr2ilr <- function(X, d1, V2) {
    .Call('_RcppCoDA_alr2ilr', PACKAGE = 'RcppCoDA', X, d1, V2)
}

#' @rdname convert_coda
#' @export
ilrvar2ilrvar <- function(Sigma, V1, V2) {
    .Call('_RcppCoDA_ilrvar2ilrvar', PACKAGE = 'RcppCoDA', Sigma, V1, V2)
}

#' @rdname convert_coda
#' @export
ilrvar2clrvar <- function(Sigma, V1) {
    .Call('_RcppCoDA_ilrvar2clrvar', PACKAGE = 'RcppCoDA', Sigma, V1)
}

#' @rdname convert_coda
#' @export
clrvar2ilrvar <- function(Sigma, V2) {
    .Call('_RcppCoDA_clrvar2ilrvar', PACKAGE = 'RcppCoDA', Sigma, V2)
}

#' @rdname convert_coda
#' @export
alrvar2clrvar <- function(Sigma, d1) {
    .Call('_RcppCoDA_alrvar2clrvar', PACKAGE = 'RcppCoDA', Sigma, d1)
}

#' @rdname convert_coda
#' @export
clrvar2alrvar <- function(Sigma, d2) {
    .Call('_RcppCoDA_clrvar2alrvar', PACKAGE = 'RcppCoDA', Sigma, d2)
}

#' @rdname convert_coda
#' @export
alrvar2alrvar <- function(Sigma, d1, d2) {
    .Call('_RcppCoDA_alrvar2alrvar', PACKAGE = 'RcppCoDA', Sigma, d1, d2)
}

#' @rdname convert_coda
#' @export
ilrvar2alrvar <- function(Sigma, V1, d2) {
    .Call('_RcppCoDA_ilrvar2alrvar', PACKAGE = 'RcppCoDA', Sigma, V1, d2)
}

#' @rdname convert_coda
#' @export
alrvar2ilrvar <- function(Sigma, d1, V2) {
    .Call('_RcppCoDA_alrvar2ilrvar', PACKAGE = 'RcppCoDA', Sigma, d1, V2)
}

